### ISSUE TITLE
发现疑似有猜局面

### ISSUE THREAD

**Issue by ouuan** [eee555/Solvable-Minesweeper#1]
![board](https://user-images.githubusercontent.com/30581822/77916343-8562e580-72cb-11ea-9e60-dda2c85f004a.png)

不知道是我看错了/想错了，还是我对“无猜”理解有误，还是确实出了 bug。

我在 EXCEL 中摆出了一些可能的局面，每个未确定的格子都可能有雷：

![solutions](https://user-images.githubusercontent.com/30581822/77916301-70865200-72cb-11ea-990a-77e724f37052.png)

**Comment by ouuan** [comment]
另外，我在生成这一局时使用的参数比较严苛，是没有找到无猜局面就会放弃找且正常开局吗？

![image](https://user-images.githubusercontent.com/30581822/77916759-2c478180-72cc-11ea-8be4-db7c907dbb4d.png)

**Comment by ouuan** [comment]
![image](https://user-images.githubusercontent.com/30581822/77916937-73357700-72cc-11ea-92f8-4b7507693345.png)

这个是点炸后雷的分布。

**Comment by eee555** [comment]
是的，版本1.1在找不到無猜时会生成有猜，版本1.2进行了更新

**Comment by eee555** [comment]
感谢您的反馈，但是您发的图片我看不到哦。目前在枚举法判雷的部分确实有一个数组越界的小bug，但是出现概率很小，本打算过几个版本再解决哦。如果您还能发现其他bug对本项目一定是一个较大的帮助呢。

**Comment by ouuan** [comment]
> 感谢您的反馈，但是您发的图片我看不到哦。

您说的是哪张图片？本 issue 内的一些图片吗？都是一些描述那一局有猜的图片。

**Comment by eee555** [comment]
好的，现在弄明白了，是我的浏览器的问题。更换浏览器后看到了您发的哪些图片。我的回答是，是的，这个版本在找不到无猜时会直接生成有猜，但是更新后目前已经能够下方输出文本信息。当找不到无猜时，文本会输出failure!

**Comment by ouuan** [comment]
比起现在这个提示我更想要一个提示 fail 的 messagebox，然后不开局。

感觉可以作为一个设置中的选项？（在下方显示是否成功 / 失败时弹出警告框并不开局）

**Comment by eee555** [comment]
嗯嗯，可以考虑这种设计，感谢您的反馈！
