### ISSUE TITLE
AttributeError: module 'minesweeper_master' has no attribute 'ai'

### ISSUE THREAD

**Issue by T0nyX1ang** [eee555/Solvable-Minesweeper#10]
复现方法：
1. git clone https://github.com/eee555/Solvable-Minesweeper.git
2. cd toolib
3. cargo build --release
4. 把新生成的ms_toollib.dll重命名为pyd，移动至根目录 
5. py -3 main.py
6. 点击左键，出现AttributeError: module 'minesweeper_master' has no attribute 'ai'

p.s.
目前直接git clone会报没法import那个rust写的dll，所以就重新编译了一下。

p.p.s.
翻了一下，发现minesweeper_master里面没有ai这个方法。

**Comment by eee555** [comment]
很抱歉给您带来这样的困扰。由于一直只有我自己开发，就没在意github上的代码。目前是有错误的，也一直没管。
最近代码改动有点大，主要是在改整个局面的控件，从原来的480个QLabel改成一个QWidget。
等会把最近代码都传上去，确保你们能跑通。

**Comment by eee555** [comment]
现在应该能跑通了。目前局面控件已经基本改好，正在做弱无猜的debug

**Comment by T0nyX1ang** [comment]
我也能跑通了，好耶，谢谢大佬！那这个issue我先关了~
