### ISSUE TITLE
Feature: 一些只跟持续开发有关的建议

### ISSUE THREAD

**Issue by T0nyX1ang** [eee555/Solvable-Minesweeper#11]
+ 希望支持例如Github Actions这样的自动构建功能，持续跟踪每次迭代的更新。
+ git仓库下载的时候有20M，不知道是不是每次更新都提交了不同的二进制文件，这个大小可能过大了。

如果我本地能运行这个程序的话，我可以PR一下（可惜目前并不能）。

**Comment by eee555** [comment]
感谢您的建议，我去学一下。
我是在windows用GitHub Desktop提交的代码，每次都是直接粘贴、替换。之后我会关注git仓库的大小。

**Comment by T0nyX1ang** [comment]
检查了一下，其实貌似pyd文件可以不用每次更新的，因为在其它机器上还是得重新编译的，但是这个应该占用的空间不会太大。

**Comment by eee555** [comment]
为了防止有人不想装rust。。

**Comment by T0nyX1ang** [comment]
啊这，如果用git clone来安装，应该默认有能力装rust吧（笑）
不过问题是，我直接git clone下来还是没法用，还是得装rust

**Comment by T0nyX1ang** [comment]
我用`git rev-list`翻了一下以前的提交记录，发现好像黑猫的v1版本是直接放在项目里面的，然后这个二进制文件被提交到了项目里面，因为git是增量更新的，这个文件现在仍然在备份中。有两个选择，您可以根据自己的需求来取舍：
- 重新建一个项目，里面完全不提交任何二进制代码（建议pyd也不要了），只提交黑猫的源码部分，然后删掉这个项目
- 利用`git filter-branch`来删掉这个文件，具体可以见[这里](https://docs.github.com/cn/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

**Comment by eee555** [comment]
如果再建一个仓库，.ui文件、图片这些还要放进去吗？

**Comment by T0nyX1ang** [comment]
图片的话最好还是放进去，不过可以考虑在根目录下面放。（这一部分我也不算太清楚）
然后ui文件的话，建议不要去动pyuic5生成的代码，可能每次生成的不一样会改一堆。
此外，貌似有一个用pyrcc5生成的qrc文件不在仓库里面，那个文件好像还挺大来着。

**Comment by eee555** [comment]
目前仓库被我减小到3M了，我以后也会注意项目的大小。Github Actions有点难写，有空再弄。

**Comment by T0nyX1ang** [comment]
仓库目前大小没问题了，然后现在我可以PR来实现一个github actions，但是需要您提供一下在当前的文件环境下，pyinstaller的打包指令，目前项目里面的打包指令貌似还没法完全打包好。

p.s. 我已经PR了一些小的修改。

**Comment by T0nyX1ang** [comment]
#13 已完成此目标
