### ISSUE TITLE
判雷出错

### ISSUE THREAD

**Issue by hyg009** [eee555/Solvable-Minesweeper#14]
v2.2.5 强无猜
![Snipaste_2021-05-03_16-24-48](https://user-images.githubusercontent.com/83577730/116857609-ad8be900-ac2f-11eb-8b5d-6c1d6b6ceb8e.png)
新手上路，被这一下炸蒙了。

**Comment by eee555** [comment]
感谢您的使用！

这个bug在qq群中已经被报告。由于比较严重，在2.2.6中进行了尝试性的修复。所以目前在2.2.6中应该是正常的，至少目前还没有玩家向我报告 。

**Comment by eee555** [comment]
对此类严重的bug，向来有着最高的处理优先级，同时感谢您的issue！

**Comment by hyg009** [comment]
v2.2.6-alpha 强无猜
![Snipaste_2021-05-04_08-05-28](https://user-images.githubusercontent.com/83577730/116947653-e5d30c00-acaf-11eb-97e1-7c24784c07ad.png)
2.2.6中还是出现了问题

**Comment by hyg009** [comment]
可能是我的扫雷习惯不是很好，这类bug出现的概率还是很高

**Comment by eee555** [comment]
感谢您的反馈，对软件的迭代升级很有帮助！这确实是一个bug，可能某个算法还有漏洞。将在两三个版本内被修改。

**Comment by eee555** [comment]
已解决啦
