### ISSUE TITLE
[2.2.6]尝试次数不符

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#15]
**系统信息**
Windows 10

**描述bug**
复现过程：自定义16\*30/150。尝试次数20000，显示`Failure! 尝试次数2001`

**截图**
![image](https://user-images.githubusercontent.com/44583944/121570658-fc405600-ca19-11eb-9b51-94e2730ddaa9.png)

![image](https://user-images.githubusercontent.com/44583944/121570633-f0ed2a80-ca19-11eb-93ea-3e14aa744680.png)

![image](https://user-images.githubusercontent.com/44583944/121570457-c56a4000-ca19-11eb-939a-c645005ffbe7.png)

**备注**
输入其他的尝试次数，显示的都是十分之一

**Comment by eee555** [comment]
是的，这是由于埋雷用了10个线程并行计算的原因。这里的尝试次数是指第一个找到无猜局面的线程的尝试次数，不作为正式的输出信息。一直计划替换掉，不过目前为止还没想到好的方案。
