### ISSUE TITLE
[2.2.6] 枚举长度过长或尝试次数过高导致闪退

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#16]
**系统信息**
Windows 10

**描述bug**
自定义16\*30/150，竞速无猜。输入尝试次数2000000，枚举长度最高35，否则闪退；输入尝试次数200000，枚举长度最高40，否则闪退；输入尝试次数20000，枚举长度最高44，否则闪退。

**Comment by eee555** [comment]
感谢，之前我还没有发现过这个问题。目前还在写截图算概率的OBR（Optical Board Recognition）功能，已经完成了70%。计划下个版本推出OBR等新功能，下下个版本主要来处理这些bug。
