### ISSUE TITLE
[possible bug?]有没有可能`xyisJudgeable`?中存在一个bug？

### ISSUE THREAD

**Issue by gepcel** [eee555/Solvable-Minesweeper#17]
在玩一个与此bug可能无关的[修改版本](https://github.com/gepcel/Solvable-Minesweeper/commit/216c0fa8b70d15e012072124ffcbe798086ebd71)（水平有限不能100%确定无关），强猜模式时，很小机率遇到猜雷时游戏崩溃，错误信息及崩溃时游戏界面如下：

```
Traceback (most recent call last):
  File "C:\python\project\Solvable-Minesweeper-master\src\mineSweeperGUI.py", line 212, in mineAreaLeftRelease
    failflag = self.ai(i, j)
  File "C:\python\project\Solvable-Minesweeper-master\src\mineSweeperGUI.py", line 175, in ai
    if minesweeper_master.xyisJudgeable(self.boardofGame, i, j):
  File "C:\python\project\Solvable-Minesweeper-master\src\minesweeper_master.py", line 426, in xyisJudgeable
    Matrix_as, Matrix_xs, Matrix_bs, _ = refresh_matrixs(BoardofGame)
ValueError: too many values to unpack (expected 4)
```

![](https://user-images.githubusercontent.com/4179106/150243412-ab0a6c5c-71f1-4035-90be-f38b92321cb0.png)

翻看了源码，在[minesweeper_master.py 71行](https://github.com/eee555/Solvable-Minesweeper/blob/f350195a998a3be13d1eea1ef37b14c3208b86ca/src/minesweeper_master.py#L71)注释信息中，提到此函数返回6个值，但在[lib.rs](https://github.com/eee555/Solvable-Minesweeper/blob/master/toollib/src/lib.rs#L33)中，貌似返回了5个值，但看不懂rust。

如果此处是我理解错了，那就很可能是我的修改引进的错误，能否麻烦帮忙看一下？

**Comment by eee555** [comment]
简单地说，可以尝试把
Matrix_as, Matrix_xs, Matrix_bs, _ = refresh_matrixs(BoardofGame)
改为
Matrix_as, Matrix_xs, Matrix_bs = refresh_matrixs(BoardofGame)

发生这个错误的原因是，我一直在写这个工具箱，暂时没有管这个游戏，使得工具箱的发展远远超过了本游戏的发展。工具箱里的api一直在变换，而我又不知道有人用，所以无暇通知。目前已经把这个工具箱独立出了新的repository，在[这里](https://github.com/eee555/ms_toollib)。最全面的文档在[这里](https://docs.rs/ms_toollib)。
然而目前认为refresh_matrixs这样的方法仍然过于底层，不宜放置在python代码里，这些底层的方法未来将全部隐藏到这个工具箱里，便于统一维护。

**Comment by gepcel** [comment]
因为这个是概率出现的，所以不好验证。不过基本上能肯定，不是多一个，而是少一个。所以应该是：
 ```
Matrix_as, Matrix_xs, Matrix_bs, _, _ = refresh_matrixs(BoardofGame)
```

另外有没有哪里有文档解释一下，最后得分的雷达图及各项分值是什么意义？

**Comment by eee555** [comment]
什么是单击模拟双击，是不是左键数字代替双击数字？此类非标准的设计，与本项目的设计理念相悖，不接受此类修改的。但是如果改成Matrix_as, Matrix_xs, Matrix_bs, _, _ = refresh_matrixs(BoardofGame)就能解决，可以提交一下，虽然很小，但是感觉参与贡献的人越多越好~甚至有注释也可以提交，感谢~

**Comment by eee555** [comment]
还有，底层的算法目前是没有发现bug的
