### ISSUE TITLE
这个局面为什么会被判负呢？有没有什么办法重新测试一遍

### ISSUE THREAD

**Issue by gepcel** [eee555/Solvable-Minesweeper#19]
强无猜局，这样的个书面，感觉是可以开啊，结果被判负了，为什么？
另外相同局面有办法重玩一次不？
![{452($~OO%FTH SP40IZQ X](https://user-images.githubusercontent.com/4179106/151290870-83de0a45-d6ed-451c-bbb5-003d3fd30a43.png)

**Comment by eee555** [comment]
“强无猜局，这样的个书面，感觉是可以开啊，结果被判负了，为什么？” -> 非常感谢您的这个报告，发生这样的情况是我意料之外的，现在就来处理。
“相同局面有办法重玩一次不？” -> 考虑过此类设计，但是不认为这是关键痛点，不想把功能做得太琐碎。目前，想重玩必须要改代码。当然，如果有好的设计欢迎提意见。

**Comment by eee555** [comment]
可能要3.0版一起更新了，因为最近强无猜的算法改进了，写了个求出所有非雷的位置的函数，以后会用这个，不容易出bug

**Comment by gepcel** [comment]
ok，那就期待 3.0 版了。这个issue你要关就关掉，想等3.0出了再关也随意你。

另外，纯好奇，假设针对这个问题你找到原因做出了修改，要怎么测试这个问题解决了呢？不是要模拟出一个同样的局面测试么？

重玩一次的说法，只是报告这个问题之前，其实我也没有太确定，想着可能是我自己哪里没玩明白。顺便问问如果有这个功能，我就能再确定一遍。真正的对重玩的功能，其实没什么需求，重玩也没太大意义。不必在意。

**Comment by gepcel** [comment]
翻了翻 issue，这个问题跟 #14 是一样的。那个关掉了，这个也关掉吧。
