### ISSUE TITLE
疑似判雷错误

### ISSUE THREAD

**Issue by gepcel** [eee555/Solvable-Minesweeper#20]
强无猜，这样的局面，貌似不应该判负

![E)5JZ}HMDRNKGTRX(RYT%ZB](https://user-images.githubusercontent.com/4179106/151466359-1287c75b-3563-43c4-8f61-064e38189673.png)

**Comment by eee555** [comment]
是的，这个和之前的一样的，还是不能立即解决的，可以开着直到解决为止

**Comment by eee555** [comment]
现在应该没这类问题了，关闭了啊
