### ISSUE TITLE
少放一颗雷，导致无法出成绩

### ISSUE THREAD

**Issue by gepcel** [eee555/Solvable-Minesweeper#21]
如图：
![微信图片_20220128152459](https://user-images.githubusercontent.com/4179106/151505696-ee6327dd-b79e-41a2-bd0e-5c71551503fe.png)

**Comment by eee555** [comment]
什么意思，没听懂。。

**Comment by eee555** [comment]
不过突然发现，这个貌似不是2.4.1版本的？虽然我知道2.4.1被报毒的问题很严重

**Comment by gepcel** [comment]
局面结束应该出来分数雷达图（自动弹窗已经设为1了），但是没有出来。不过后来发现可能是另一个原因，该打开的方块已经全部打开了，但雷有几颗不影响判断的没标雷。所以最后游戏完成后，不出分数。

**Comment by eee555** [comment]
好的，这个同样是没有注意到的，可能是bug。按理结束的标志就是点开所有非雷，这是标准。

**Comment by eee555** [comment]
这个应该也解决了，关闭了啊，感谢测试
