### ISSUE TITLE
矢量贴图？

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#22]
可以改尺寸的前提下如果用位图看起来会怪怪的。是否考虑用矢量图？

**Comment by putianyi889** [comment]
我可以研究一下矢量图。需要什么格式的？正好在做一个latex摆雷宏包也需要做矢量图

**Comment by eee555** [comment]
SVg格式，谢谢啦

**Comment by putianyi889** [comment]
施工中https://github.com/eee555/Solvable-Minesweeper/pull/24

**Comment by eee555** [comment]
辛苦辛苦~

**Comment by putianyi889** [comment]
当前任务已完成
