### ISSUE TITLE
回放录像时光标坐标不对

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#28]
**系统信息**
Windows 10/Ubuntu, etc.

**描述bug**
光标坐标应该对应贴图左上角，实际似乎对应了贴图中心

**截图**
![image](https://user-images.githubusercontent.com/44583944/233781587-f8a3f673-629b-4329-8af2-19693e78f218.png)

**备注**
(无)

**Comment by eee555** [comment]
收到，感谢

**Comment by eee555** [comment]
已解决
