### ISSUE TITLE
可能存在的崩溃bug

### ISSUE THREAD

**Issue by Yoyal** [eee555/Solvable-Minesweeper#31]
**系统信息**
Windows 10 22H2

**描述bug**
在强无猜和弱无猜模式中，点击到不一定是雷的格子中，游戏必然会崩溃。

**截图**
![QQ截图20230912002015](https://github.com/eee555/Solvable-Minesweeper/assets/61278440/164541ca-045d-47c1-a787-b9fc857c16e8)

**备注**
不清楚是属于bug还是程序特性

**Comment by eee555** [comment]
收到，感谢您的反馈！

**Comment by eee555** [comment]
在release版本里有这个bug，在nightly版本里正常。还需要继续跟踪观察。
