### ISSUE TITLE
强无猜的一个可能无解的情况？

### ISSUE THREAD

**Issue by gepcel** [eee555/Solvable-Minesweeper#33]
强无猜模式，基本上是默认设置。

![image](https://github.com/eee555/Solvable-Minesweeper/assets/4179106/eefc5fb4-ae7a-4eec-922b-5710c22c4dfb)

![image](https://github.com/eee555/Solvable-Minesweeper/assets/4179106/e8d487c7-fde8-4f0c-a881-578ae064d4ae)

**Comment by eee555** [comment]
这个是有解的。
事实上，按照高级的配置（16行30列99雷），目前都没有发现无解的局面，总的来是可靠的（雷数再多会无解，有两种算法）。
看不出来的话，可以按下“ctrl+空格”，启动截屏计算概率（当网页缩放为100%时，我这里可以用）。

**Comment by gepcel** [comment]
我好像漏看了一个格。

**Comment by gepcel** [comment]
这种情况呢？
![image](https://github.com/eee555/Solvable-Minesweeper/assets/4179106/f5fa8ab2-f91e-4531-bf73-4cd3b67fa679)
