### ISSUE TITLE
破纪录界面信息优化

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#36]
**内容**
显示`旧纪录 → 新纪录  ↑差值`

**是否可以自行实现想法**
~~`我觉得我行`~~
应该是在做这个的时候顺便做的，那我应该不用管了
https://github.com/eee555/Solvable-Minesweeper/blob/48d6b04a28bed6745c8215c5655c4c00f27bfd35/src/main.py#L32C1-L32C16

**Comment by eee555** [comment]
这句话什么意思我突然看不懂了（这种情况不多），但肯定不是这个意思。
关于这个问题，我认为第一，提高不大，希望玩家在看见破纪录信息后仍然保留一丝期待“到底破了多少？”；第二，增大了界面展示信息的复杂度，希望做得简介美观一点，因此很难设计。
如果你能实现，我会合并。
但是实现是有难度的，特别是你需要下载一个qt设计师，先修改.ui文件再改.py文件，当然我可以提供技术支持
