### ISSUE TITLE
弱无猜bug

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#37]
**系统信息**
Windows 10/Ubuntu, etc.

**描述bug**
一个明显的死猜炸掉

**截图**
![456eceb773b5679bd98f2c62fbcf787d](https://github.com/eee555/Solvable-Minesweeper/assets/44583944/b3c0023a-cafb-4a3d-8a3d-1d1667be34f0)

**备注**
(无)

**Comment by eee555** [comment]
已解决
