### ISSUE TITLE
Currently unusable on wine-9.14 on arch linux

### ISSUE THREAD

**Issue by ralokt** [eee555/Solvable-Minesweeper#42]
I'm gonna put a collection of things I noticed when trying to use the application on my fairly bare-bones linux setup here.

**系统信息**
wine-9.14 on arch linux/openbox

**描述bug**
The application crashed on first startup, producing the following popup:
![image](https://github.com/user-attachments/assets/964f112a-7480-4492-a7b0-aea5bf01c249)

It does start up after that, however, making a pure left mouse click anywhere on the standard minesweeper UI produces a crash. By that I mean:
 - placing flags works
 - chording "works" and produces a 3x3 pressed area
 - pressing the left mouse button works, the smiley enters its ":O" state
 - however, once you release the left mouse button, the application crashes
 - all of this happens when you click outside the board, but inside the area where the standard minesweeper UI we know from winmine is drawn - ie, on the edges, in the title bar with the smiley, or on the smiley. The menu bar is unaffected, as is the bottom bar with the username, and the white square that is probably for the user's flag?

Speaking of the flag:
Most menus work. However, the dropdown to select a country doesn't - I can manually type into it, though. Settings are remembered.

Also, what I presume is the counters window is empty, and clicking below the bar produces this:
![image](https://github.com/user-attachments/assets/b8fb8136-9c76-4f53-8ba8-6bcd52b6b068)

Also, this is with the language set to english, ie, the counter window title isn't translated.

Settings are remembered, though!

**截图**
see above (since there's more than one, it seemed more readable that way)

**备注**
I understand if supporting wine is a non-goal for this project, but not knowing that, I'll just document what happens if you do try to use it there - I understand if this results in `wontfix`, tho.

**Comment by eee555** [comment]
It is theoretically possible to run on wine. But I don't have a physical ubuntu machine at the moment, so I can't debug it.

If the crash occurs when the left button releases, the most likely is the lack of the "SetWindowDisplayAffinity" api. And this api is known not available before Windows 7.

If the underlying api is complete, I think wine should be one of the goals; Otherwise, it shouldn't be the goal because of security.

**Comment by eee555** [comment]
> Also, this is with the language set to english, ie, the counter window title isn't translated.

Done.

**Comment by ralokt** [comment]
That makes sense! Thanks - closing this, then :)
