### ISSUE TITLE
界面Ui问题

### ISSUE THREAD

**Issue by ljzloser** [eee555/Solvable-Minesweeper#44]
1、很多按钮点击没有视觉反馈，建议增加视觉反馈。
2、国家和地区选择，下拉列表没有补全提示，建议可以补全提示。
3、最小化后点击任务栏图标无法一次性恢复正常，需要人为选择窗口，并且选择其中一个窗口其余窗口并不会一起显示。建议将非主窗口设置为dialog 移除任务栏图标。

**Comment by eee555** [comment]
> 很多按钮点击没有视觉反馈，建议增加视觉反馈。

确定和取消没有高亮是故意设计的，强调反应快。

> 国家和地区选择，下拉列表没有补全提示，建议可以补全提示。

目前挺好的，补全容易补错。

> 建议将非主窗口设置为dialog 移除任务栏图标。

可以。

**Comment by eee555** [comment]
> 最小化后点击任务栏图标无法一次性恢复正常，需要人为选择窗口，并且选择其中一个窗口其余窗口并不会一起显示。建议将非主窗口设置为dialog 移除任务栏图标。

已解决
