### ISSUE TITLE
屏幕缩放率如果不是100，且勾选鼠标不能移除边界会导致鼠标边界范围判断错误的bug

### ISSUE THREAD

**Issue by ljzloser** [eee555/Solvable-Minesweeper#49]
**系统信息**
win11

**描述bug**
屏幕缩放率如果不是100，且勾选鼠标不能移除边界会导致鼠标边界范围判断错误的bug

**截图**
如果提供截图反馈会更好~

**备注**
Qt 在windows上，很多情况都会导致这个bug，建议在程序启动时添加临时环境变量，锁死DPI,示例代码
import os
os.environ["QT_FONT_DPI"] = "96"
添加到app启动前即可解决。这是最简单的解决方案，其他解决方案如果要跟随缩放需要考虑的比较多。

**Comment by eee555** [comment]
已解决
