### ISSUE TITLE
试玩了一下，提几个建议

### ISSUE THREAD

**Issue by T0nyX1ang** [eee555/Solvable-Minesweeper#5]
1. 至少在“经典”和“竞速无猜”模式下，可能在标记双击**未打开局面**时，按下方格的阴影没有恢复，请见下图左中下方的321。目前我慢速进行了一些测试，但是在慢速操作时没有出现这个问题，但是在点击速度加快时会出现这个问题，不知道是不是这方面的原因。
![shading](https://user-images.githubusercontent.com/33901373/89916457-2ffbf500-dc2a-11ea-800a-b7322998ef6f.png)
2. 希望能加入F2,1,2,3这样的快捷键以便快速重开。
3. 提议：下面那个没想好写什么的框里面可以写本局游戏的参数（bvs之类的）。
4. 提议：对于有python的用户，建议clone仓库，然后直接使用如下命令:
```bash
    pip install PyQt5
```
5. 提议：目前的代码因为判断条件很多，希望能优化一下

**Comment by eee555** [comment]
首先非常感谢您的建议！
1、这条反馈非常重要，是之前还没有发现的；会在若干版本以后解决。
2、会在一到二个版本以内解决。
3、感觉只写3bvs的话内容有点少，希望能更美观一些，展示一些和arbiter不一样的更高级的东西，目前还没有成熟的想法，干脆空着。
5、您看得非常仔细！目前的代码绝大部分已经代表了本人的最高水平，有些地方已经是牺牲效率换取可读性+可靠性，难以优化，建议直接将其看成黑箱。但是如果有关于具体哪一块代码的建议也很乐意尝试一下！
