### ISSUE TITLE
竞速无猜bug？

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#6]
不是很确定啥是竞速无猜（个人认为是不需要数雷的无猜
![image](https://user-images.githubusercontent.com/44583944/102110914-a5244480-3e2d-11eb-8ebb-5bcb03dcf0bd.png)

**Comment by putianyi889** [comment]
这个局面明显是死猜。也有可能是超过了最大尝试次数。希望在超过最大尝试次数的情况下输出警告。

**Comment by eee555** [comment]
这是超过了最大尝试次数，因为算法是随机埋雷并删选，当雷数超过110时，无猜的可能性极小。解决这一问题的思路有两条，一是发提示，二是改成更快速鲁棒的算法。后者更好，但在3.0之前都还没列入计划（3.0计划加入AI教练），除非有人合作开发。如果雷数较大，当前阶段建议是用弱可猜。然而，2.1.2以前的版本的弱可猜有小bug，不过这个问题在暂未发布的2.2版本中会被解决。
