### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by zjpAAA** [eee555/Solvable-Minesweeper#8]
python版本3.7，pyqt版本5.9.2，用pyuic重新生成的.py打包后提示出错，提示“‘QLabel’ object has no attribute 'leftRelease'”。
好像是.ui文件不是最新版本的问题，用pyuic生成的.py和您提供的.py不一致。
另外，uiFiles文件夹里提供的文件少了一个selfDefinedParameter.ui。
请问可以分享一下吗？

**Comment by eee555** [comment]
1、关于“用pyuic生成的.py和您提供的.py不一致”，原因是pyuic生成的.py我又改了一下，这样做是因为.ui文件直的生成的.py不能满足满足要求，有些代码必须自己写。如果有直接生成改动代码的方法，我也很乐意学习。
2、selfDefinedParameter.ui与一个计划删除的功能有关。原先计划的一个功能是按一下快捷键就可以快捷地打开网页，例如扫雷网，但是现在感觉这个功能不是那么必要，计划删除。selfDefinedParameter.ui用来设置打开网页的URL、页面放大倍数，快捷键等。所以目前我在自己电脑里都已经删了，抱歉无法提供了。

**Comment by zjpAAA** [comment]
谢谢
