### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by putianyi889** [eee555/Solvable-Minesweeper#9]
![B1P0H0~5CBP3}TLR)0)HSX1](https://user-images.githubusercontent.com/44583944/110960621-d803a900-8346-11eb-8f92-954e8656dfcb.png)

**Comment by eee555** [comment]
收到，感谢您的宝贵意见

**Comment by eee555** [comment]
我这边无法复现？

**Comment by eee555** [comment]
我知道了，这是缺少防呆设计导致的。他肯定是沿用了高级的设置，指定了3BV在100到381之间，所以一直弄不出来。。
